"""initial schema

Revision ID: 1b9a0914276e
Revises: 
Create Date: 2026-03-26 01:18:52.880658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b9a0914276e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain', postgresql.ENUM('ETHEREUM', 'POLYGON', 'BSC', 'SOLANA', name='chain_enum'), nullable=False),
    sa.Column('rpc_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ws_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_synced_block', sa.BIGINT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tx_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('price_usd', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('max_wallets', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('chain', postgresql.ENUM('ETHEREUM', 'POLYGON', 'BSC', 'SOLANA', name='chain_enum'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=True),
    sa.Column('last_checked_block', sa.BIGINT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracked_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_wallets_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_wallets_user_id'), ['user_id'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('LARGE_TX', 'TOKEN_TRANSFER', 'WALLET_ACTIVITY', name='alert_type_enum'), nullable=False),
    sa.Column('threshold_amount', sa.NUMERIC(precision=30, scale=10), nullable=True),
    sa.Column('token_symbol', sa.VARCHAR(length=50), nullable=True),
    sa.Column('webhook_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['tracked_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('from_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('to_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=30, scale=10), nullable=False),
    sa.Column('token_symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('direction', postgresql.ENUM('IN', 'OUT', name='tx_direction_enum'), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['tracked_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_block_number'), ['block_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tx_hash'), ['tx_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('alert_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['tracked_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_logs')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_transactions_block_number'))

    op.drop_table('transactions')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_wallet_id'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('tracked_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_wallets_user_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_wallets_address'))

    op.drop_table('tracked_wallets')
    op.drop_table('subscriptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_table('payments')
    op.drop_table('chain_configs')
    # ### end Alembic commands ###
